---
# tasks file for vault-compose-up
---
- name: Ingress | Setup and run ingress
  become: yes
  become_method: sudo
  block:
    - name: Create target directory
      file: 
        path: "{{ dest_path }}"
        state: directory 
        mode: '0755'

    - name: Copy compose file and volumes to target host
      copy:
        src: "{{ item }}"
        dest: "{{ dest_path }}"
        owner: deploy
        group: deploy
        mode: 0644
      with_fileglob:
        - "{{ role_path }}/files/*"

    - name: Template a compose files to dest_path on target host
      template:
        src: "{{ role_path }}/templates/{{ item.name }}.j2"
        dest: "{{ item.dest }}/{{ item.name }}"
        # dest: "{{ item.dest }}/{{ project_name }}.yaml"
        # dest: "{{ dest_path }}/{{ role_name }}.yaml"
        owner: deploy
        group: deploy
        mode: '0644'
      with_items:
        - { name: "docker-compose.yaml", dest: "{{ dest_path }}" }
        - { name: "vault.json", dest: "{{ dest_path }}/volumes/config/" }

    - name: Log into DockerHub
      docker_login:
        registry: "{{ docker_registry.url }}"
        username: "{{ docker_registry.user }}"
        password: "{{ docker_registry.password }}" 

    - name: Stop vault container if it runs
      community.general.docker_compose:
        project_src: "{{ dest_path }}"
        files: "{{ role_name }}.yaml"
        project_name: "{{ project_name }}"
        remove_orphans: yes
        stopped: yes
      tags:
        - molecule-idempotence-notest

    - name: Deploy vault from a compose file
      community.general.docker_compose:
        project_src: "{{ dest_path }}"
        files: "{{ role_name }}.yaml"
        recreate: always
      tags:
        - molecule-idempotence-notest


