---
# tasks file for vault-compose-up
- name: Vault | Setup and run vault
  become: yes
  become_method: sudo
  block:
    - name: Create target directories
      file: 
        path: "{{ item }}"
        state: directory 
        mode: '0755'
        group: deploy
        owner: deploy
      with_items:
        - "{{ dest_path }}"
        - "{{ dest_path }}/volumes"
        - "{{ dest_path }}/volumes/file"
        - "{{ dest_path }}/volumes/config"
        - "{{ dest_path }}/volumes/tls"
        - "{{ dest_path }}/volumes/logs"

    - name: Copy volumes to target host
      copy:
        src: "{{ item }}"
        dest: "{{ dest_path }}"
        owner: deploy
        group: deploy
        mode: 0644
      with_fileglob:
        - "{{ role_path }}/files/*"

    - name: Template compose file and vault config to their destinations on target host
      template:
        src: "{{ role_path }}/templates/{{ item.name }}.j2"
        dest: "{{ item.dest }}/{{ item.name }}"
        owner: deploy
        group: deploy
        mode: '0644'
      with_items:
        - { name: "vault-compose-up.yaml", dest: "{{ dest_path }}" }
        - { name: "vault.json", dest: "{{ dest_path }}/volumes/config" }

    - name: Log into DockerHub
      docker_login:
        registry: "{{ docker_registry.url }}"
        username: "{{ docker_registry.user }}"
        password: "{{ docker_registry.password }}" 

    - name: Stop vault container if it runs
      community.general.docker_compose:
        project_src: "{{ dest_path }}"
        files: "{{ role_name }}.yaml"
        project_name: "{{ project_name }}"
        remove_orphans: yes
        stopped: yes
      tags:
        - molecule-idempotence-notest

    - name: Deploy vault from a compose file
      community.general.docker_compose:
        project_src: "{{ dest_path }}"
        files: "{{ role_name }}.yaml"
        recreate: always
      tags:
        - molecule-idempotence-notest


