version: '2'
services:
  vault:
    image: vault
    container_name: vault
    ports:
      - "8200:8200"
    restart: always
    environment:
      VAULT_CACERT: "/vault/tls/ca.pem"
      VAULT_ADDR: "https://key-vault.sandbox.net:8200"
      #VAULT_API_ADDR: "https://key-vault.sandbox.net:8200"
    volumes:
      - ./volumes/logs:/vault/logs
      - ./volumes/file:/vault/file
      - ./volumes/config:/vault/config
      - ./volumes/tls:/vault/tls
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json
